// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0aoTayjibEP6sxg-I08e7_vBZ0MKuhoU',
    appId: '1:1092845158524:web:149c18fcb4ac1bc0bf89f9',
    messagingSenderId: '1092845158524',
    projectId: 'shoe-store-app-68a1f',
    authDomain: 'shoe-store-app-68a1f.firebaseapp.com',
    storageBucket: 'shoe-store-app-68a1f.firebasestorage.app',
    measurementId: 'G-7DDTWCJ7Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_BP1cDyUCqoy_nzVKWdZp_LcdW9jBEfw',
    appId: '1:1092845158524:android:4c05b0dcb6ca2cf3bf89f9',
    messagingSenderId: '1092845158524',
    projectId: 'shoe-store-app-68a1f',
    storageBucket: 'shoe-store-app-68a1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsJ9tnn17fKG1ZhMiA2tITTTmlrr5zfU8',
    appId: '1:1092845158524:ios:0157d0b97523b8ffbf89f9',
    messagingSenderId: '1092845158524',
    projectId: 'shoe-store-app-68a1f',
    storageBucket: 'shoe-store-app-68a1f.firebasestorage.app',
    iosBundleId: 'com.example.utsShoeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsJ9tnn17fKG1ZhMiA2tITTTmlrr5zfU8',
    appId: '1:1092845158524:ios:0157d0b97523b8ffbf89f9',
    messagingSenderId: '1092845158524',
    projectId: 'shoe-store-app-68a1f',
    storageBucket: 'shoe-store-app-68a1f.firebasestorage.app',
    iosBundleId: 'com.example.utsShoeStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0aoTayjibEP6sxg-I08e7_vBZ0MKuhoU',
    appId: '1:1092845158524:web:eb0f39f020de119cbf89f9',
    messagingSenderId: '1092845158524',
    projectId: 'shoe-store-app-68a1f',
    authDomain: 'shoe-store-app-68a1f.firebaseapp.com',
    storageBucket: 'shoe-store-app-68a1f.firebasestorage.app',
    measurementId: 'G-4K1KFPG10M',
  );
}
